services:
  backend:
    image: node:latest
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3333:3333"
    command: sh -c "npm install && npm run start"
    networks: 
      - mynetwork

  frontend:
    image: node:latest
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    networks: 
      - mynetwork
    depends_on:
      - backend

networks:
  mynetwork:
    driver: bridge